name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_DEPLOY_KEY }}

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_PUBLIC_IP }}
          USER: ubuntu
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            if [ ! -d "/home/ubuntu/app" ]; then
              mkdir -p /home/ubuntu/app
              git clone git@github.com:bhaggat/portfolio-node.git /home/ubuntu/app
            else
              cd /home/ubuntu/app
              git pull origin main
            fi
            cd /home/ubuntu/app
            npm install --omit=dev
            pm2 stop all || true
            pm2 start index.js --name "node-api"
          EOF
